engines:
  eslint:
    enabled: true
    channel: 'eslint-9'
    config:
      config: 'eslint.config.mjs'

checks:
  method-lines:
    config:
      threshold: 50
  method-complexity:
    config:
      threshold: 20
  file-lines:
    config:
      threshold: 500

ratings:
  paths:
    - '*.js'
