engines:
  eslint:
    enabled: true
    channel: 'eslint-8'
    config:
      config: '.eslintrc.yaml'

checks:
  method-lines:
    config:
      threshold: 50
  method-complexity:
    config:
      threshold: 20
  file-lines:
    config:
      threshold: 500

ratings:
  paths:
    - '*.js'
